package com.sbd.bhuvi.mapper;

import com.sbd.bhuvi.dto.UserDto;
import com.sbd.bhuvi.model.User;

public class UserMapper {

    public static UserDto mapToUserDto(User user) {
        return new UserDto(
                user.getId(), // Long
                user.getName(), // String
                user.getContactNumber(), // String
                user.getEmailId(), // String
                user.getOwner() // String
        );
    }

    public static User mapToUser(UserDto userDto) {
        return new User(
                userDto.getName(), // String
                userDto.getContactNumber(), // String
                userDto.getEmailId(), // String
                userDto.getOwner() // String
        );
        // Do not set ID; it will be generated by the database
    }
}
